### ISSUE TITLE
reversal example fails in the wild

### ISSUE THREAD

**Issue by bmcfee** [algorithmic-music-exploration/amen#30]
```
 1  ⌂ py35   master ×  ~/git/amen/amen/examples 
 →  python reverse.py  ~/git/librosa/tests/data/test1_44100.wav 
/home/bmcfee/miniconda/envs/py35/lib/python3.5/site-packages/scipy/sparse/compressed.py:739: SparseEfficiencyWarning: Changing the sparsity structure of a csr_matrix is expensive. lil_matrix is more efficient.
  SparseEfficiencyWarning)
Traceback (most recent call last):
  File "reverse.py", line 19, in <module>
    out = synthesize(beats)
  File "/home/bmcfee/git/amen/amen/synthesize.py", line 92, in synthesize
    sparse_array[1, right_start:right_end] += resampled_audio[1]
  File "/home/bmcfee/miniconda/envs/py35/lib/python3.5/site-packages/scipy/sparse/csr.py", line 272, in __getitem__
    return self._get_row_slice(row, col)
  File "/home/bmcfee/miniconda/envs/py35/lib/python3.5/site-packages/scipy/sparse/csr.py", line 353, in _get_row_slice
    row_slice = self._get_submatrix(i, cslice)
  File "/home/bmcfee/miniconda/envs/py35/lib/python3.5/site-packages/scipy/sparse/csr.py", line 420, in _get_submatrix
    check_bounds(j0, j1, N)
  File "/home/bmcfee/miniconda/envs/py35/lib/python3.5/site-packages/scipy/sparse/csr.py", line 415, in check_bounds
    " %d <= %d" % (i0, num, i1, num, i0, i1))
IndexError: index out of bounds: 0 <= 52919990 <= 52920000, 0 <= 88360 <= 52920000, 52919990 <= 88360
```

**Comment by tkell** [comment]
:bug:

**Comment by tkell** [comment]
Fixed with https://github.com/algorithmic-music-exploration/amen/pull/31

**Comment by tkell** [comment]
As per my comment on #31, I am going to close this and open a new bug / PR for the mono issue!
